name: DeployReleaseZip
permissions: read-all | write-all
on:
  pull_request:
    types: [closed]
  workflow_dispatch:
jobs:
  if_merged:
    if: github.event.pull_requested.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: action-zip
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r Ruehrstaat_Systems_Connector.zip Ruehrstaat_Systems_connector
  if_dispatched:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: action-zip
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r Ruehrstaat_Systems_Connector.zip Ruehrstaat_Systems_connector
      - name: Push
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Release commit of Deployment Workflow'
